version: "3.9"
services:
  localstack:
    image: fetchdocker/data-takehome-localstack
    ports:
      - 4566:4566
  postgres:
    image: fetchdocker/data-takehome-postgres
    ports:
      - 5432:5432
  main:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    network_mode: host
    volumes:
      - /Users/littlecharmandar/Downloads/fetch:/code
